// <auto-generated />
using System;
using HospitalManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HospitalManagement.Models.Admission", b =>
                {
                    b.Property<int>("AdmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdmissionId"));

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdmissionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NurseID")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("AdmissionId");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("NurseID");

                    b.HasIndex("PatientId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("HospitalManagement.Models.Allergy", b =>
                {
                    b.Property<int>("AllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllergyId"));

                    b.Property<string>("AlleryStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AllergyId");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            AllergyId = 1,
                            AlleryStatus = "Active",
                            Description = "Allergic reaction to penicillin-based antibiotics",
                            Name = "Penicillin"
                        },
                        new
                        {
                            AllergyId = 2,
                            AlleryStatus = "Active",
                            Description = "Skin irritation or respiratory issues from latex exposure",
                            Name = "Latex"
                        },
                        new
                        {
                            AllergyId = 3,
                            AlleryStatus = "Active",
                            Description = "Severe anaphylactic reaction to peanuts",
                            Name = "Peanuts"
                        },
                        new
                        {
                            AllergyId = 4,
                            AlleryStatus = "Active",
                            Description = "Sneezing, congestion, or asthma from dust exposure",
                            Name = "Dust Mites"
                        },
                        new
                        {
                            AllergyId = 5,
                            AlleryStatus = "Active",
                            Description = "Swelling or anaphylaxis after insect stings",
                            Name = "Bee Stings"
                        },
                        new
                        {
                            AllergyId = 6,
                            AlleryStatus = "Delete",
                            Description = "Severe allergic reaction to crustaceans and mollusks",
                            Name = "Shellfish"
                        },
                        new
                        {
                            AllergyId = 7,
                            AlleryStatus = "Active",
                            Description = "Digestive issues or skin reactions from egg consumption",
                            Name = "Eggs"
                        },
                        new
                        {
                            AllergyId = 8,
                            AlleryStatus = "Delete",
                            Description = "Lactose intolerance or dairy protein allergy",
                            Name = "Milk/Dairy"
                        },
                        new
                        {
                            AllergyId = 9,
                            AlleryStatus = "Active",
                            Description = "Respiratory or skin reactions to aspirin and NSAIDs",
                            Name = "Aspirin"
                        },
                        new
                        {
                            AllergyId = 10,
                            AlleryStatus = "Delete",
                            Description = "Anaphylactic reaction to almonds, walnuts, cashews",
                            Name = "Tree Nuts"
                        },
                        new
                        {
                            AllergyId = 11,
                            AlleryStatus = "Active",
                            Description = "Seasonal allergic rhinitis and hay fever symptoms",
                            Name = "Pollen"
                        },
                        new
                        {
                            AllergyId = 12,
                            AlleryStatus = "Delete",
                            Description = "Allergic reaction to iodine-based contrast agents",
                            Name = "Iodine"
                        },
                        new
                        {
                            AllergyId = 13,
                            AlleryStatus = "Delete",
                            Description = "Skin rash or severe reactions to sulfonamide antibiotics",
                            Name = "Sulfa Drugs"
                        },
                        new
                        {
                            AllergyId = 14,
                            AlleryStatus = "Active",
                            Description = "Contact dermatitis from nickel-containing metals",
                            Name = "Nickel"
                        },
                        new
                        {
                            AllergyId = 15,
                            AlleryStatus = "Delete",
                            Description = "Respiratory symptoms from cat and dog allergens",
                            Name = "Pet Dander"
                        });
                });

            modelBuilder.Entity("HospitalManagement.Models.Bed", b =>
                {
                    b.Property<int>("BedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BedId"));

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BedStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("BedId");

                    b.HasIndex("WardId");

                    b.ToTable("Beds");

                    b.HasData(
                        new
                        {
                            BedId = 1,
                            BedNumber = "G1",
                            BedStatus = "Active",
                            Status = "Available",
                            WardId = 1
                        },
                        new
                        {
                            BedId = 2,
                            BedNumber = "G2",
                            BedStatus = "Active",
                            Status = "Available",
                            WardId = 1
                        },
                        new
                        {
                            BedId = 3,
                            BedNumber = "ICU1",
                            BedStatus = "Active",
                            Status = "Available",
                            WardId = 2
                        },
                        new
                        {
                            BedId = 4,
                            BedNumber = "S1",
                            BedStatus = "Active",
                            Status = "Available",
                            WardId = 3
                        },
                        new
                        {
                            BedId = 5,
                            BedNumber = "S2",
                            BedStatus = "Active",
                            Status = "Available",
                            WardId = 3
                        },
                        new
                        {
                            BedId = 6,
                            BedNumber = "G3",
                            BedStatus = "Delete",
                            Status = "Available",
                            WardId = 1
                        },
                        new
                        {
                            BedId = 7,
                            BedNumber = "ICU2",
                            BedStatus = "Delete",
                            Status = "Available",
                            WardId = 2
                        },
                        new
                        {
                            BedId = 8,
                            BedNumber = "ICU3",
                            BedStatus = "Active",
                            Status = "Available",
                            WardId = 2
                        },
                        new
                        {
                            BedId = 9,
                            BedNumber = "S3",
                            BedStatus = "Delete",
                            Status = "Available",
                            WardId = 3
                        },
                        new
                        {
                            BedId = 10,
                            BedNumber = "P1",
                            BedStatus = "Active",
                            Status = "Available",
                            WardId = 4
                        });
                });

            modelBuilder.Entity("HospitalManagement.Models.BedAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignmentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BedId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("BedId");

                    b.HasIndex("PatientId");

                    b.ToTable("BedAssignments");
                });

            modelBuilder.Entity("HospitalManagement.Models.Condition", b =>
                {
                    b.Property<int>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionId"));

                    b.Property<string>("ConditionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ConditionId");

                    b.ToTable("Conditions");

                    b.HasData(
                        new
                        {
                            ConditionId = 1,
                            ConditionStatus = "Active",
                            Description = "Chronic blood sugar condition",
                            Name = "Diabetes"
                        },
                        new
                        {
                            ConditionId = 2,
                            ConditionStatus = "Active",
                            Description = "High blood pressure",
                            Name = "Hypertension"
                        },
                        new
                        {
                            ConditionId = 3,
                            ConditionStatus = "Active",
                            Description = "Respiratory condition",
                            Name = "Asthma"
                        },
                        new
                        {
                            ConditionId = 4,
                            ConditionStatus = "Active",
                            Description = "Joint inflammation",
                            Name = "Arthritis"
                        },
                        new
                        {
                            ConditionId = 5,
                            ConditionStatus = "Active",
                            Description = "Neurological disorder",
                            Name = "Epilepsy"
                        },
                        new
                        {
                            ConditionId = 6,
                            ConditionStatus = "Delete",
                            Description = "Cardiovascular disorders and heart conditions",
                            Name = "Heart Disease"
                        },
                        new
                        {
                            ConditionId = 7,
                            ConditionStatus = "Active",
                            Description = "Progressive loss of kidney function",
                            Name = "Chronic Kidney Disease"
                        },
                        new
                        {
                            ConditionId = 8,
                            ConditionStatus = "Delete",
                            Description = "Chronic obstructive pulmonary disease",
                            Name = "COPD"
                        },
                        new
                        {
                            ConditionId = 9,
                            ConditionStatus = "Active",
                            Description = "Mental health disorder affecting mood",
                            Name = "Depression"
                        },
                        new
                        {
                            ConditionId = 10,
                            ConditionStatus = "Delete",
                            Description = "Excessive worry and fear responses",
                            Name = "Anxiety Disorder"
                        },
                        new
                        {
                            ConditionId = 11,
                            ConditionStatus = "Delete",
                            Description = "Brain injury due to interrupted blood supply",
                            Name = "Stroke"
                        },
                        new
                        {
                            ConditionId = 12,
                            ConditionStatus = "Delete",
                            Description = "Malignant tumor growth and spread",
                            Name = "Cancer"
                        },
                        new
                        {
                            ConditionId = 13,
                            ConditionStatus = "Delete",
                            Description = "Bone density loss and fracture risk",
                            Name = "Osteoporosis"
                        },
                        new
                        {
                            ConditionId = 14,
                            ConditionStatus = "Active",
                            Description = "Severe recurring headaches with neurological symptoms",
                            Name = "Migraine"
                        },
                        new
                        {
                            ConditionId = 15,
                            ConditionStatus = "Active",
                            Description = "Stomach acid flowing back into esophagus",
                            Name = "Gastroesophageal Reflux"
                        });
                });

            modelBuilder.Entity("HospitalManagement.Models.Consumable", b =>
                {
                    b.Property<int>("ConsumableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumableId"));

                    b.Property<string>("ConsumableStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConsumableId");

                    b.ToTable("Consumables");

                    b.HasData(
                        new
                        {
                            ConsumableId = 1,
                            ConsumableStatus = "Active",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Disposable gloves",
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gloves",
                            Quantity = 200,
                            Type = "Medication"
                        },
                        new
                        {
                            ConsumableId = 2,
                            ConsumableStatus = "Active",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sterile syringes",
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Syringes",
                            Quantity = 150,
                            Type = "Diagnostic"
                        },
                        new
                        {
                            ConsumableId = 3,
                            ConsumableStatus = "Active",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Absorbent sheets",
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Linen Savers",
                            Quantity = 300,
                            Type = "Surgical"
                        },
                        new
                        {
                            ConsumableId = 4,
                            ConsumableStatus = "Active",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "IV administration sets",
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "IV Drip Set",
                            Quantity = 75,
                            Type = "Other"
                        },
                        new
                        {
                            ConsumableId = 5,
                            ConsumableStatus = "Active",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Surgical face masks",
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Face Masks",
                            Quantity = 500,
                            Type = "Diagnostic"
                        });
                });

            modelBuilder.Entity("HospitalManagement.Models.Discharge", b =>
                {
                    b.Property<int>("DischargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DischargeId"));

                    b.Property<DateOnly>("DischargeDate")
                        .HasColumnType("date");

                    b.Property<string>("DischargeStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("WardAdminId")
                        .HasColumnType("int");

                    b.HasKey("DischargeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PatientId");

                    b.ToTable("Discharges");
                });

            modelBuilder.Entity("HospitalManagement.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EmailVerificationTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailVerificationTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsTwoFactorEnabled")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetPin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPinExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoFactorRecoveryCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoFactorSecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            Email = "admin@example.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Admin",
                            Gender = "Male",
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "User",
                            PasswordHash = "Password123",
                            Role = "ADMINISTRATOR",
                            UserName = "adminuser"
                        },
                        new
                        {
                            EmployeeID = 2,
                            Email = "nurse1@example.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Nina",
                            Gender = "Male",
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Nurse",
                            PasswordHash = "Password123",
                            Role = "NURSE",
                            UserName = "nurse1"
                        },
                        new
                        {
                            EmployeeID = 3,
                            Email = "doctor1@example.com",
                            FailedLoginAttempts = 0,
                            FirstName = "David",
                            Gender = "Male",
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "Doctor",
                            PasswordHash = "Password123",
                            Role = "DOCTOR",
                            UserName = "doctor1"
                        },
                        new
                        {
                            EmployeeID = 4,
                            Email = "scriptmgr@example.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Sara",
                            Gender = "Male",
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "ScriptManager",
                            PasswordHash = "Password123",
                            Role = "SCRIPTMANAGER",
                            UserName = "scriptmgr"
                        },
                        new
                        {
                            EmployeeID = 5,
                            Email = "consumablemgr@example.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Chris",
                            Gender = "Male",
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "ConsumableManager",
                            PasswordHash = "Password123",
                            Role = "CONSUMABLESMANAGER",
                            UserName = "consumablemgr"
                        },
                        new
                        {
                            EmployeeID = 6,
                            Email = "wardadmin@example.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Wanda",
                            Gender = "Male",
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "WardAdmin",
                            PasswordHash = "Password123",
                            Role = "WARDADMIN",
                            UserName = "wardadmin"
                        },
                        new
                        {
                            EmployeeID = 7,
                            Email = "nursingsister@example.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Nancy",
                            Gender = "Male",
                            IsActive = "Active",
                            IsTwoFactorEnabled = "False",
                            LastName = "NursingSister",
                            PasswordHash = "Password123",
                            Role = "NURSINGSISTER",
                            UserName = "nursingsister"
                        });
                });

            modelBuilder.Entity("HospitalManagement.Models.HospitalInfo", b =>
                {
                    b.Property<int>("HospitalInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalInfoId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HospitalInfoStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("HospitalInfoId");

                    b.ToTable("HospitalInfos");
                });

            modelBuilder.Entity("HospitalManagement.Models.LoginAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Success")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoginAudits");
                });

            modelBuilder.Entity("HospitalManagement.Models.Medication", b =>
                {
                    b.Property<int>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicationId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicationId");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            MedicationId = 1,
                            Description = "Pain relief and fever reducer",
                            ExpiryDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicationStatus = "Active",
                            Name = "Paracetamol",
                            Quantity = 1000,
                            Type = "Prescription"
                        },
                        new
                        {
                            MedicationId = 2,
                            Description = "Anti-inflammatory",
                            ExpiryDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicationStatus = "Active",
                            Name = "Ibuprofen",
                            Quantity = 800,
                            Type = "Other"
                        },
                        new
                        {
                            MedicationId = 3,
                            Description = "Strong painkiller (controlled)",
                            ExpiryDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicationStatus = "Active",
                            Name = "Morphine",
                            Quantity = 100,
                            Type = "Supplement"
                        },
                        new
                        {
                            MedicationId = 4,
                            Description = "Antibiotic",
                            ExpiryDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicationStatus = "Active",
                            Name = "Amoxicillin",
                            Quantity = 500,
                            Type = "Prescription"
                        },
                        new
                        {
                            MedicationId = 5,
                            Description = "Used for anxiety and seizures",
                            ExpiryDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicationStatus = "Active",
                            Name = "Diazepam",
                            Quantity = 300,
                            Type = "OverTheCounter"
                        },
                        new
                        {
                            MedicationId = 6,
                            Description = "Broad-spectrum antibiotic",
                            ExpiryDate = new DateTime(2027, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicationStatus = "Active",
                            Name = "Ciprofloxacin",
                            Quantity = 400,
                            Type = "Prescription"
                        },
                        new
                        {
                            MedicationId = 7,
                            Description = "Allergy relief",
                            ExpiryDate = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicationStatus = "Active",
                            Name = "Loratadine",
                            Quantity = 600,
                            Type = "OverTheCounter"
                        },
                        new
                        {
                            MedicationId = 8,
                            Description = "Used to treat type 2 diabetes",
                            ExpiryDate = new DateTime(2027, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicationStatus = "Active",
                            Name = "Metformin",
                            Quantity = 700,
                            Type = "Prescription"
                        },
                        new
                        {
                            MedicationId = 9,
                            Description = "Used to treat acid reflux",
                            ExpiryDate = new DateTime(2027, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicationStatus = "Active",
                            Name = "Omeprazole",
                            Quantity = 450,
                            Type = "Prescription"
                        },
                        new
                        {
                            MedicationId = 10,
                            Description = "Bronchodilator for asthma",
                            ExpiryDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicationStatus = "Active",
                            Name = "Salbutamol",
                            Quantity = 350,
                            Type = "Prescription"
                        });
                });

            modelBuilder.Entity("HospitalManagement.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsDeletedByReceiver")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("IsDeletedBySender")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("IsGroupMessage")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("IsRead")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("SentDate");

                    b.HasIndex("SenderId", "IsDeletedBySender");

                    b.HasIndex("SenderId", "SentDate");

                    b.HasIndex("ReceiverId", "IsDeletedByReceiver", "ReadDate");

                    b.HasIndex("ReceiverId", "IsRead", "SentDate");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("HospitalManagement.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("ActionUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MessageId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationId");

                    b.HasIndex("AdmissionId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("PatientId");

                    b.HasIndex("ReadDate");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("ReceiverId", "IsActive", "ReadDate");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HospitalManagement.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Cellphone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GetStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Cellphone = "0812345678",
                            DOB = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Test",
                            Gender = "Male",
                            GetStatus = "Active",
                            IdNumber = "0000000000000",
                            LastName = "Patient"
                        },
                        new
                        {
                            PatientId = 2,
                            Cellphone = "0823456789",
                            DOB = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lerato",
                            Gender = "Female",
                            GetStatus = "Active",
                            IdNumber = "9505201234087",
                            LastName = "Mokoena"
                        },
                        new
                        {
                            PatientId = 3,
                            Cellphone = "0834567890",
                            DOB = new DateTime(1988, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sizwe",
                            Gender = "Male",
                            GetStatus = "Active",
                            IdNumber = "8811105674085",
                            LastName = "Dlamini"
                        },
                        new
                        {
                            PatientId = 4,
                            Cellphone = "0845678901",
                            DOB = new DateTime(2002, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thandi",
                            Gender = "Female",
                            GetStatus = "Active",
                            IdNumber = "0203157890083",
                            LastName = "Ngubane"
                        },
                        new
                        {
                            PatientId = 5,
                            Cellphone = "0856789012",
                            DOB = new DateTime(1990, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nomsa",
                            Gender = "Female",
                            GetStatus = "Delete",
                            IdNumber = "9007251234089",
                            LastName = "Mthembu"
                        },
                        new
                        {
                            PatientId = 6,
                            Cellphone = "0867890123",
                            DOB = new DateTime(1985, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mandla",
                            Gender = "Male",
                            GetStatus = "Delete",
                            IdNumber = "8512055678091",
                            LastName = "Khumalo"
                        },
                        new
                        {
                            PatientId = 7,
                            Cellphone = "0878901234",
                            DOB = new DateTime(1998, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Precious",
                            Gender = "Female",
                            GetStatus = "Delete",
                            IdNumber = "9809187890085",
                            LastName = "Sithole"
                        },
                        new
                        {
                            PatientId = 8,
                            Cellphone = "0889012345",
                            DOB = new DateTime(1992, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bongani",
                            Gender = "Male",
                            GetStatus = "Delete",
                            IdNumber = "9204125674087",
                            LastName = "Ndlovu"
                        },
                        new
                        {
                            PatientId = 9,
                            Cellphone = "0890123456",
                            DOB = new DateTime(1987, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zanele",
                            Gender = "Female",
                            GetStatus = "Delete",
                            IdNumber = "8708301234083",
                            LastName = "Mahlangu"
                        },
                        new
                        {
                            PatientId = 10,
                            Cellphone = "0801234567",
                            DOB = new DateTime(1993, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sipho",
                            Gender = "Male",
                            GetStatus = "Delete",
                            IdNumber = "9301225678089",
                            LastName = "Radebe"
                        },
                        new
                        {
                            PatientId = 11,
                            Cellphone = "0812345679",
                            DOB = new DateTime(1996, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Lindiwe",
                            Gender = "Female",
                            GetStatus = "Active",
                            IdNumber = "9606087890081",
                            LastName = "Cele"
                        },
                        new
                        {
                            PatientId = 12,
                            Cellphone = "0823456780",
                            DOB = new DateTime(1989, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Themba",
                            Gender = "Male",
                            GetStatus = "Active",
                            IdNumber = "8910145674085",
                            LastName = "Zulu"
                        },
                        new
                        {
                            PatientId = 13,
                            Cellphone = "0834567891",
                            DOB = new DateTime(2001, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nonhlanhla",
                            Gender = "Female",
                            GetStatus = "Delete",
                            IdNumber = "0102281234087",
                            LastName = "Maseko"
                        },
                        new
                        {
                            PatientId = 14,
                            Cellphone = "0845678902",
                            DOB = new DateTime(1994, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mthunzi",
                            Gender = "Male",
                            GetStatus = "Delete",
                            IdNumber = "9411035678083",
                            LastName = "Shabalala"
                        });
                });

            modelBuilder.Entity("HospitalManagement.Models.PatientAllergy", b =>
                {
                    b.Property<int>("PatientAllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientAllergyId"));

                    b.Property<int>("AllergyId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientAllergyId");

                    b.HasIndex("AllergyId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientAllergies");
                });

            modelBuilder.Entity("HospitalManagement.Models.PatientCondition", b =>
                {
                    b.Property<int>("PatientConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientConditionId"));

                    b.Property<int>("ConditionId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientConditionId");

                    b.HasIndex("ConditionId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientConditions");
                });

            modelBuilder.Entity("HospitalManagement.Models.PatientFolder", b =>
                {
                    b.Property<int>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FolderId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpenedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FolderId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientFolders");
                });

            modelBuilder.Entity("HospitalManagement.Models.PatientMedication", b =>
                {
                    b.Property<int>("PatientMedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientMedicationId"));

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientMedicationId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientMedications");
                });

            modelBuilder.Entity("HospitalManagement.Models.PatientMovement", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovementId"));

                    b.Property<string>("MovementStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MovementTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("MovementId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientMovements");
                });

            modelBuilder.Entity("HospitalManagement.Models.TrustedDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TrustedDevices");
                });

            modelBuilder.Entity("HospitalManagement.Models.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("HospitalManagement.Models.Ward", b =>
                {
                    b.Property<int>("WardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WardId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WardStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WardId");

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            WardId = 1,
                            Capacity = 10,
                            Description = "Basic treatment ward",
                            WardName = "General Ward",
                            WardStatus = "Active"
                        },
                        new
                        {
                            WardId = 2,
                            Capacity = 5,
                            Description = "Intensive care unit",
                            WardName = "ICU",
                            WardStatus = "Active"
                        },
                        new
                        {
                            WardId = 3,
                            Capacity = 8,
                            Description = "For surgical patients",
                            WardName = "Surgical Ward",
                            WardStatus = "Active"
                        },
                        new
                        {
                            WardId = 4,
                            Capacity = 12,
                            Description = "Children and adolescent care",
                            WardName = "Pediatric Ward",
                            WardStatus = "Active"
                        },
                        new
                        {
                            WardId = 5,
                            Capacity = 15,
                            Description = "Maternity and newborn care",
                            WardName = "Maternity Ward",
                            WardStatus = "Active"
                        },
                        new
                        {
                            WardId = 6,
                            Capacity = 8,
                            Description = "Heart and cardiovascular patients",
                            WardName = "Cardiology Ward",
                            WardStatus = "Delete"
                        },
                        new
                        {
                            WardId = 7,
                            Capacity = 10,
                            Description = "Bone and joint surgery patients",
                            WardName = "Orthopedic Ward",
                            WardStatus = "Active"
                        },
                        new
                        {
                            WardId = 8,
                            Capacity = 6,
                            Description = "Cancer treatment and care",
                            WardName = "Oncology Ward",
                            WardStatus = "Delete"
                        },
                        new
                        {
                            WardId = 9,
                            Capacity = 20,
                            Description = "Emergency and trauma patients",
                            WardName = "Emergency Ward",
                            WardStatus = "Active"
                        },
                        new
                        {
                            WardId = 10,
                            Capacity = 8,
                            Description = "Brain and nervous system disorders",
                            WardName = "Neurology Ward",
                            WardStatus = "Delete"
                        },
                        new
                        {
                            WardId = 11,
                            Capacity = 12,
                            Description = "Mental health and psychiatric care",
                            WardName = "Psychiatric Ward",
                            WardStatus = "Active"
                        },
                        new
                        {
                            WardId = 12,
                            Capacity = 14,
                            Description = "Elderly patient care",
                            WardName = "Geriatric Ward",
                            WardStatus = "Delete"
                        },
                        new
                        {
                            WardId = 13,
                            Capacity = 10,
                            Description = "Physical therapy and recovery",
                            WardName = "Rehabilitation Ward",
                            WardStatus = "Delete"
                        });
                });

            modelBuilder.Entity("HospitalManagement.ViewModel.Login", b =>
                {
                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RememberDevice")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("RememberMe")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("UserNameorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("HospitalManagement.Models.Admission", b =>
                {
                    b.HasOne("HospitalManagement.Models.Employee", "Doctor")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Models.Employee", "Nurse")
                        .WithMany()
                        .HasForeignKey("NurseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Models.Patient", "Patient")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagement.Models.Bed", b =>
                {
                    b.HasOne("HospitalManagement.Models.Ward", "Ward")
                        .WithMany("Beds")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("HospitalManagement.Models.BedAssignment", b =>
                {
                    b.HasOne("HospitalManagement.Models.Bed", "Bed")
                        .WithMany()
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bed");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagement.Models.Discharge", b =>
                {
                    b.HasOne("HospitalManagement.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Models.Patient", "Patient")
                        .WithMany("Discharges")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagement.Models.Message", b =>
                {
                    b.HasOne("HospitalManagement.Models.Employee", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Models.Employee", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("HospitalManagement.Models.Notification", b =>
                {
                    b.HasOne("HospitalManagement.Models.Admission", "Admission")
                        .WithMany()
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HospitalManagement.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HospitalManagement.Models.Employee", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Models.Employee", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admission");

                    b.Navigation("Patient");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("HospitalManagement.Models.PatientAllergy", b =>
                {
                    b.HasOne("HospitalManagement.Models.Allergy", "Allergy")
                        .WithMany()
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Models.Patient", "Patient")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagement.Models.PatientCondition", b =>
                {
                    b.HasOne("HospitalManagement.Models.Condition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Models.Patient", "Patient")
                        .WithMany("PatientConditions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagement.Models.PatientFolder", b =>
                {
                    b.HasOne("HospitalManagement.Models.Patient", "Patient")
                        .WithMany("PatientFolders")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagement.Models.PatientMedication", b =>
                {
                    b.HasOne("HospitalManagement.Models.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Models.Patient", "Patient")
                        .WithMany("PatientMedications")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagement.Models.PatientMovement", b =>
                {
                    b.HasOne("HospitalManagement.Models.Patient", "Patient")
                        .WithMany("PatientMovements")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalManagement.Models.TrustedDevice", b =>
                {
                    b.HasOne("HospitalManagement.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HospitalManagement.Models.UserPreference", b =>
                {
                    b.HasOne("HospitalManagement.Models.Employee", "Employee")
                        .WithOne("Preferences")
                        .HasForeignKey("HospitalManagement.Models.UserPreference", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HospitalManagement.Models.Employee", b =>
                {
                    b.Navigation("Preferences");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("HospitalManagement.Models.Patient", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Discharges");

                    b.Navigation("PatientAllergies");

                    b.Navigation("PatientConditions");

                    b.Navigation("PatientFolders");

                    b.Navigation("PatientMedications");

                    b.Navigation("PatientMovements");
                });

            modelBuilder.Entity("HospitalManagement.Models.Ward", b =>
                {
                    b.Navigation("Beds");
                });
#pragma warning restore 612, 618
        }
    }
}
